services:
  backend:
    build: .
    restart: unless-stopped
    ports:
      - '127.0.0.1:4000:4000'
    volumes:
      - ./logs:/app/logs
    networks:
      - xd-network
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: laba
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "laba", "-U", "dev" ]
      timeout: 3s
      retries: 10
    networks:
      - xd-network
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dj@arbuz.pro
      PGADMIN_DEFAULT_PASSWORD: asdasd
    networks:
      - xd-network
    depends_on:
      postgres:
        condition: service_healthy

networks:
  xd-network:
    driver: bridge